# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: python C:\agent\custom_folder_script\mypy.py $(Build.Repository.Name)
  displayName: 'Run a one-line script'

- script: |
    echo Was it a Success.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- publish: '$(Build.ArtifactStagingDirectory)/*'
    displayName: 'Publish script'
    artifact: EAR
