# Starter pipeline
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Free Trial(02f0e468-f8d5-41ed-b7ef-da557e4b2995)'
    KeyVaultName: 'haider-vault'
    SecretsFilter: '*'
    RunAsPreJob: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: python C:\agent\custom_folder_script\mypy.py $(Build.Repository.Name)
  displayName: 'Run a one-line script'

- script: |
    echo Was it a Success with pipeline id $(System.PlanId).
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- publish: '$(Build.ArtifactStagingDirectory)\EAR'
  displayName: 'Publish script'
  artifact: EAR

- task: CmdLine@2
  inputs:
    script: 'echo $(Password) > secret.txt'

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: UniversalPackages@0
  displayName: Artifact Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)\EAR'
    vstsFeedPublish: 'MyFirstProject/earFeed'
    vstsFeedPackagePublish: ear-http-starter-01
    packagePublishDescription: 'The EAR Description'